import os
from sqlalchemy.ext.asyncio import create_async_engine, async_sessionmaker, AsyncSession
from sqlalchemy.orm import declarative_base

# 1. Retrieve the connection string injected by Docker Compose
DATABASE_URL = os.environ.get("DATABASE_URL")

if not DATABASE_URL:
    raise ValueError("⚠️ DATABASE_URL environment variable not found. Check your docker-compose.yml and .env files.")

# 2. Create the Asynchronous Engine
# echo=True prints raw SQL queries generated by the ORM to the terminal (great for debugging)
engine = create_async_engine(DATABASE_URL, echo=True)

# 3. Session Factory (SessionMaker)
# expire_on_commit=False is crucial in async contexts to prevent SQLAlchemy 
# from trying to reload object attributes after the transaction is closed.
async_session_maker = async_sessionmaker(
    engine, 
    class_=AsyncSession, 
    expire_on_commit=False
)

# 4. Base class from which all our relational models will inherit
Base = declarative_base()

# 5. Dependency Injection for FastAPI
async def get_db():
    """
    Provides a database session for each individual HTTP request 
    and automatically closes it upon completion, preventing memory leaks.
    """
    async with async_session_maker() as session:
        yield session