version: '3.8'

services:
  api_backend:
    build: .
    image: cloven_base_image
    container_name: cloven_viscount_api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - CHROMA_DB_DIR=/app/chroma_db
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_data:/app/chroma_db

  ui_frontend:
    image: cloven_base_image
    container_name: cloven_viscount_ui
    restart: unless-stopped
    ports:
      - "8501:8501"
    command: streamlit run frontend.py --server.address 0.0.0.0
    depends_on:
      - api_backend