version: '3.8'

services:
  api_backend:
    build: .
    container_name: cv_analyzer_container
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_data:/app/chroma_db

  ui_frontend:
    build: .
    container_name: cloven_viscount_ui
    restart: unless-stopped
    ports:
      - "8501:8501"
    command: streamlit run frontend.py --server.address 0.0.0.0
    depends_on:
      - api_backend